### ISSUE TITLE
Electricity Disconnected icon does not blink on Thrower inserters

### ISSUE THREAD

**Issue by SteamPunker39** [Kiplacon/RenaiTransportation#12]
When A Thrower Inserter is not connected to electricity the powercord Icon does not blink, unlike all other vanilla tiles.

**Comment by Kiplacon** [comment]
It's related to an old issue where inserters that were low on power and were moving very slowly would cause their arms to stretch really far. It's been a while since Ive thought about it, though now that I am I might have some ideas on other methods that could keep the fix and make the icon blink again.

**Comment by Kiplacon** [comment]
guess what's finally fixed 2.5 years later
