### ISSUE TITLE
Train signals cause mid-jump trains to go backwards

### ISSUE THREAD

**Issue by Xcelled** [Kiplacon/RenaiTransportation#9]
It's me again!

Ran into another weird speed issue. In certain cases, if trains hit a signal after jumping, while part of the train is still in the air, they may spontaneously do the "abrupt reversal" thing when they hit the signal, which destroys the train.

Here's an example of this happening, at 10% game speed: https://i.imgur.com/N5hNR9r.gif

Removing the signal lets the train through umolested. As far as I can tell, this happens when the train is followed by a second train, as it is in the attached example save.

The save file is here: 
[supplylines.zip](https://github.com/Kiplacon/Renai-Transportation/files/5426761/supplylines.zip)

To trigger the bug, click the 9 car copper ore train (near the center of the map) and tell it to go to the next station.

**Comment by Xcelled** [comment]
One idea I had for fixing this is a ghost rail car with a collision mask that excludes everything. When a car hits a ramp, it'd increment a counter on the ramp. When the car lands, it decrements the counter.

Then, as long as the counter is greater than 0, the ramp spawns the ghost rail car at its coordinates to block off the tracks so that signals placed behind the ramp will function as expected even with a train in the air.

A more complete but complicated approach would include calculating where the train will land and placing a ghost car there as well, to stop trains coming from other tracks entering the block that the jumping train is about to land in. That, plus the use of chain signals before the ramp, should cover most cases of jumping trains losing their block reservations.

**Comment by Xcelled** [comment]
Some investigation reveals that factorio doesn't like it if a rolling stock is given an empty collision mask. Instead, maybe the mod could make an always red signal at the ramp's coordinates (a la https://mods.factorio.com/mod/always_red_rail_signal) when a train goes off of it.

**Comment by Kiplacon** [comment]
I wonder why the train signal is causing it to freeze. Maybe in the moment of a backwards-facing carriage attaching, it thinks the train is facing backwards and stops it? I'll have to try your save file

**Comment by Xcelled** [comment]
I think it's actually the inverse - I think the 2nd train reserves the block (at yellow) while the first train is in the air. Upon landing, the first train sees the reserved block ahead of it and panic stops. Weirdly, the game overrides the normal deceleration and the train actually does stop for the signal. At that point, a backwards facing carriage lands and the speed logic goes "train stopped, must reverse." :boom: 

So this problem is actually a two-fer:
1. Flying trains don't exist on the rail system, so a train behind a jumping train can reserve the block ahead of the landing zone, causing the flying train to stop on a dime when it lands
2. The speed logic has another edge case :(

As I mentioned, I think problem 1 can be solved (or at least mitigated) by dropping an always-red signal at the ramp's location while a train for that ramp is in the air. Problem two probably requires a complete re-imagining of the flying state logic, in order to treat the entire train as a whole when reasoning about speed and direction, instead of deciding these properties for each individual stock.

There's a bit of an open question here: When cars are added to a train, the train's ID changes. Does this immediately invalidate the lock held by the "old" train such that the "new" train can immediately lock the block for itself? If there's any kind of delay here where the "new" train is pathing but the block is still held by the "old" train, then putting a signal within <train stopping distance> from the landing point is potentially risky, as the landing train will not be able to reserve the upcoming block and will have to slow and stop, potentially causing mayhem as its airborne carriages land on top of it.

**Comment by Xcelled** [comment]
I was able to (mostly) solve the first problem by rigging up a series of rail signals connected to an R/S latch:

![image](https://user-images.githubusercontent.com/5599341/97132520-9965ad00-171d-11eb-8a6b-1e837fcbaeb0.png)

The circuit will hold the signal in front of the ramp red as soon as it's switched to red by a passing train. Then, the chain signal is used for look ahead. Once the chain signal changes from red back to non-red (indicating the jumping train has landed **and** cleared the next signal at the far end), the signal in front of the ramp is released and any following train can approach and jump. This of course relies on there being only one block of track between the jump and the landing, and assumes that the only way to enter this block is via the ramp.

Blueprint string if you're curious:

```
0eNrVVtuOmzAQ/Zd5htWScElR1V+olH2sVsiByWYksJExUaOIf+8YNiTbkIQgVKkvSL7MmTPnjG2OsMlrLDVJA/ERKFWygvjXESr6kCK3c+ZQIsRABgtwQIrCjjJMKUPtpqrYkBRGaWgcIJnhb4i95t0BlIYMYYfWDg6JrIsNat5wD8eBUlUcqqTNznDuMnwJHDhA7K9CzsIcjVZ5ssGd2BNH8LZPnITXsja2srNb0pVJrkrZkzY1z/Qsuh2uxgw6/MoIK8irHRSl0C2xGH5wiKpNWT8Buu4gywNzq6VJtloVCUnGgHgr8gqbLqXEtOft2Y9lc6Ed8Sho3nnzwq5+aET59/qSkUinNZl2yD40jH4l/6LnKDSZXYGG0gcOnPT3XwJmkJHu2LZYQ36cgWexpEKLMj7szQapEtm4liX8XE+wLlMGmlv2jDFgcSH+GP+iG4Ytnzwvwb85L+vJ1nw5Vd8nWPM246m6Mo1vr0F7vPvu+lc4J7MfJ/VuJl2MO9P+ky3i/8dX6pzmR/NcqUHPUQvK3XQnSLqfBQ2ov+rVj4Yv1DHUvZlbKOxrKDCjunAxZxaa34ZS5ThURnRuIi5jADL6KsttQfxHgly156miNFcV9r1jdI3najWK7MZS39UTmrp9F+439RMd6E+0cdHayJvbP7P44kfOgT3qqhNv5fmR/y0KI+81DMKm+QPTimfX
```

I haven't had the problem described in the OP since installing these contraptions before heavily used ramps, so I think there's definite merit to the solution I outlined in the previous post.

As to the unanswered question, I'm nearly certain now that it's not an issue after watching several jumps before signals carefully.

**Comment by Kiplacon** [comment]
Sorry I haven't gotten back to this for a while, but I finally got a chance to go through your save and actually learned quite a bit about how factorio trains signals work and how rails are divided into blocks by the signals. I definitely agree with what you found, the first train can jump no problem when the second train isn't following it. It also helped to split the rails into more segments, for example putting another signal right in front of the ramp keeps the second train from reserving the block ahead of the landing point just long enough for the first train to go through, but then the second train takes the jump while the first train is in that block after landing point causing the second train to crash at that signal in the same way.

Not having tried it, I'm guessing having an always-red signal in front of the ramp while a train is in the air would work, but then only one (automatic) train could take the ramp at a time, which wouldn't be intuitive to players unless the ramp always came with a built in signal next to it, like the magnet ramp power buffer, and it was explained somewhere that that signal works differently to normal signals.

I'll have to think about how best to fix this, whether the always-red signal, something else, or even just leaving it as is because technically it makes sense that the signals wouldn't be able to track a train while it's in the air, and like you mentioned this case only really happens when there's only one block between jump and land. I'm personally not against leaving in ways players can make mistakes/loose trains so long as they understand how it happened, but that's certainly not clear right now for this case which contributes to making the interaction feel bad.

If you're wondering about the sudden jump backwards, it's because of this part of the control.lua code here
![image](https://user-images.githubusercontent.com/12401534/97243675-39c6da80-17cd-11eb-945c-77d3f20c6dfa.png)
When the first carriage lands, it has no speed and no reference of direction so it has to be given based on the way it's facing. After that, following trains can keep "pushing" the train with a direction based on the trains existing speed. But the way it's set up now if a following carriage connects to a train that's not moving, the 0 speed condition sets the train to negative speed which 9 times out of 10 will make the train go backwards (the 10th out of 10 time being if the front locomotive is facing backwards for some reason). I think if I just change that >0 to >=0, a train will go forward from a standstill, which I might actually change now that I think about it, I probably just wasn't thinking about a stopped train when I first wrote that 🤔

**Comment by Kiplacon** [comment]
While looking into the 0 speed thing, I just found that since I set a landing train's initial speed based on the orientation of it's first landing carriage, trains that are pushed from the back have a 50/50 chance of actually going backwards when landing based on what orientation it's first non-locomotive carriage is facing. I changed it to now reference the orientation of the ghost locomotive if it has one, and that's worked smoother

**Comment by Xcelled** [comment]
That sounds good to me - though maybe with a note in the docs that a jumping train does _not_ hold a block, and if you want to be safe, you need to manually set up circuit conditions like I demoed above.
